---
- name: Deploy application to localhost
  hosts: web  # 'web' matches the group in your hosts.ini
  become: yes
  tasks:
    - name: Copy the application WAR file
      copy:
        src: "/var/snap/jenkins/4844/workspace/MavenAnsible-CICD/target/*.war"  # Path to WAR file in Jenkins workspace
        dest: "/opt/tomcat/webapps/"  # Destination path on the local machine
    - name: Start the Tomcat server
      service:
        name: tomcat
        state: started
